INSERT INTO "sdgs" ("id", "name") VALUES(1, 'No Poverty');
INSERT INTO "sdgs" ("id", "name") VALUES(2, 'Zero Hunger');
INSERT INTO "sdgs" ("id", "name") VALUES(3, 'Good Health and Wellbeing');
INSERT INTO "sdgs" ("id", "name") VALUES(4, 'Quality Education');
INSERT INTO "sdgs" ("id", "name") VALUES(5, 'Gender Equality');
INSERT INTO "sdgs" ("id", "name") VALUES(6, 'Clean Water and Sanitation');
INSERT INTO "sdgs" ("id", "name") VALUES(7, 'Affordable and Clean Energy');
INSERT INTO "sdgs" ("id", "name") VALUES(8, 'Decent Work and Economic Growth');
INSERT INTO "sdgs" ("id", "name") VALUES(9, 'Industry Innovation and Infrastructure');
INSERT INTO "sdgs" ("id", "name") VALUES(10, 'Reduced Inequalities');
INSERT INTO "sdgs" ("id", "name") VALUES(11, 'Sustainable Cities and Communities');
INSERT INTO "sdgs" ("id", "name") VALUES(12, 'Responsible Consumption and Production');
INSERT INTO "sdgs" ("id", "name") VALUES(13, 'Climate Action');
INSERT INTO "sdgs" ("id", "name") VALUES(14, 'Life Below Water');
INSERT INTO "sdgs" ("id", "name") VALUES(15, 'Life on Land');
INSERT INTO "sdgs" ("id", "name") VALUES(16, 'Peace, Justice and Strong Institutions');
INSERT INTO "sdgs" ("id", "name") VALUES(17, 'Partnership for the Goals');
